
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  type-handlers-package: com.example.demo
  mapper-locations:
    - classpath:mapper/**/*.xml
